name: html_scraper
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  dio: ^4.0.0
  http:
  html: ^0.15.0
  xpath: ^0.1.0
  csv:
  yaml: ^3.1.0
  sprintf:
  args:
  intl:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
